services:
  webserver:
    image: "elbromasmc/jrdelperu"
    restart: unless-stopped
    build:
      context: ./src
      dockerfile: ./Dockerfile
      target: production
    environment:
      - ENV=production
    ports:
      - "8080:8080"
  db:
    restart: unless-stopped

