services:
  devrunner:
    image: "devrunner"
    build:
      context: .
      dockerfile: ./Dockerfile.dev
      args:
        - USER_UID=${USER_UID}
    volumes:
      - type: bind
        source: ./
        target: /home/devrunner/src
    restart: unless-stopped
    environment:
      - ENV=${ENV}
      - PORT=${PORT}
      - REL=${REL}
    ports:
      - "8080:8080"
      - "8010:8010"
