services:
  webserver:
    userns_mode: "keep-id:uid=1000,gid=1000"
    restart: no
    build:
      context: ./src
      dockerfile: ./Dockerfile
      target: development
    environment:
      - ENV=development
    volumes:
      - runner-home:/home/runner
      - type: bind
        source: ./src
        target: /home/runner/src
    ports:
      - "8080:8080"
      - "8010:8010"

volumes:
  runner-home:

x-podman:
  in_pod: false

