services:
  webserver:
    restart: unless-stopped
    build:
      context: ./src
      dockerfile: ./Dockerfile
      target: production
    environment:
      - ENV=production
    expose:
      - "8080"

